name: personal_web
description: My personal web for portofolio
publish_to: 'none'
version: 1.0.1+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  url_launcher: ^6.0.9
  cached_network_image: ^3.1.0
  responsive_builder: ^0.4.1
  universal_html: ^2.0.8
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  carousel_slider: ^4.0.0
  google_fonts: ^2.1.0
  animated_text_kit: ^4.2.1
  http: ^0.13.3
  bloc: ^7.1.0
  flutter_bloc: ^7.2.0
  flutter_html: any
  url_strategy: ^0.2.0
  shared_preferences: ^2.0.7
  flip_card: ^0.5.0
  mailto: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/img/projects/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
