name: personal_web
description: My personal web for portfolio
publish_to: 'none'
version: 1.6.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.4
  dyn_mouse_scroll: ^1.0.7
  get_it: ^7.2.0
  url_launcher: ^6.1.5
  cached_network_image: ^3.2.1
  responsive_builder: ^0.4.2
  universal_html: ^2.0.8
  scrollable_positioned_list: ^0.3.2
  carousel_slider: ^4.1.1
  google_fonts: ^3.0.1
  animated_text_kit: ^4.2.2
  http: ^0.13.5
  flutter_html: ^2.2.1
  url_strategy: ^0.2.0
  shared_preferences: ^2.0.15
  timeline_tile: ^2.0.0
  get: ^4.6.5
  flip_card: ^0.6.0
  mailto: ^2.0.0
  remixicon: ^1.0.0



dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/img/projects/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic

flutter_intl:                                
  enabled: true                              
  class_name: AppLocalizations                           
  main_locale: en                            
  arb_dir: lib/core/localization/app_locale        
  output_dir: lib/core/localization/generated